name: Update Scratch Cloud Status

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # allow manual run

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check cloud data
        run: |
          STATUS="down"
          if curl -s "https://clouddata.scratch.mit.edu/logs?projectid=669020072&limit=1" | jq .[0] >/dev/null 2>&1; then
            STATUS="up"
          fi
          echo "STATUS=$STATUS" >> $GITHUB_ENV

      - name: Copy correct badge
        run: |
          mkdir -p badge
          if [ "$STATUS" = "up" ]; then
            cp cloud_up.svg badge/status.svg
          else
            cp cloud_down.svg badge/status.svg
          fi

      - name: Commit & Push badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badge/status.svg
          git commit -m "Update badge: $STATUS" || exit 0
          git push
